
name: "Automatic ci"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  run_compile_ci:
    uses: ./.github/workflows/general-ci.yml
  run_test_ci:
    uses: ./.github/workflows/test.yml
