name: Docker Image CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg=ARCH=aarch64 --build-arg=LIBC=musl --tag static-python-aarch64-musl:$(date +%s) .
